const userData = {
  githubUsername: 'Ryandinulfatah12',
  name: 'Ryan',
  fullname: 'Ryan Dinul Fatah',
  title: 'Passionate Backend Developer with 2 Years Experience.',
  status: '#BackendDeveloper@SQMProperty',
  country: 'Indonesia',
  desc: 'I am currently a Backend Developer in the systems development division at SQM Property!. I love serving software that benefits people, it s my fuel. I enjoy learning about technology and business, of course in between working I improve my skills as a Backend Developer such as taking courses and one day I want to have my own team by helping with Digitalization in Indonesia and others.',
  navLink: [
    { href: '/', label: 'Ryan' },
    { href: '/about', label: 'About' },
    { href: '/work', label: 'Work' },
    { href: '/articles', label: 'Articles' },
    { href: '/achievement', label: 'Achievement' },
    { href: '/link', label: 'Get in touch' },
  ],
  project: [
    {
      id: 1,
      nama: 'Sistem pendeteksi dini pergerakan tanah longsor',
      img: '/img/project/new-longsor.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Sistem pendeteksi dini pergerakan tanah longsor SMKN 1 padaherang yang telah saya buat untuk PAMERAN SMK KARYA INOVASI (anak PKL) di STMIK AKAKOM YOGYAKARTA, alat pendeteksi yang bisa dimonitoring melalui web dengan REALTIME.',
      stack: 'C, PHP Native, MySQL, Jquery',
      url: '#',
    },
    {
      id: 2,
      nama: 'Smart Home Project',
      img: '/img/project/new-smarthome.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Karya Inovasi dari SMK Negeri 1 Padaherang, yang dimana sebuah rumah yang dilengkapi fitur canggih seperti membuka gerbang dengan HP, membuka pintu utama dengan KTP, semua lampu bisa otomatis/manual dari HP, Jemuran dan Kipas Otomatis, serta Monitoring Suhu Ruangan',
      stack: 'C, Javascript, PHP',
      url: '#',
    },
    {
      id: 3,
      nama: 'Narosan',
      img: '/img/project/new-narosan.png',
      type: 'Self Project & Brand',
      desc: 'Narosan awalnya adalah sebuah platform edukasi serta konsultasi seputar relationship, parenting, rekomendasi, informasi, special gift (kado) untuk semua orang.',
      stack: 'Wordpress',
      url: 'https://narosan.com/',
    },
    {
      id: 4,
      nama: 'Aplikasi Kasir Restourant Management',
      img: '/img/project/new-resto.png',
      type: 'Laravel Project',
      desc: 'Aplikasi Kasir Restourant Management System yang dibuat oleh Saya (Ryan Dinul Fatah) Untuk memenuhi tugas Sekolah tepatnya Project Akhir UJIKOM 2020 saya di SMKN 1 Padaherang ini.',
      stack: 'Laravel, Jquery, MySQL',
      url: 'https://github.com/Ryandinulfatah12/AplikasiKasirRestoran',
    },
    {
      id: 5,
      nama: 'Aplikasi Pengaduan Masyarakat',
      img: '/img/project/new-pengaduan.png',
      type: 'Laravel Project',
      desc: 'Aplikasi ini merupakan aplikasi yang dapat mengelola pendataan pengaduan dari masyarakat, selain dibuat sesimple mungkin, aplikasi ini juga lumayan dapat bekerja dengan baik untuk dibilang sebuah Aplikasi Pengaduan Masyarakat.',
      stack: 'Laravel, Jquery, MySQL',
      url: 'https://github.com/Ryandinulfatah12/AplikasiPengaduanMasyarakat',
    },
    {
      id: 6,
      nama: 'Sistem informasi Sekolah',
      img: '/img/project/new-sismk.png',
      type: 'Laravel Project',
      desc: 'Web Media Informasi Sekolah yang dibuat oleh Novi Herlambang . SI_SMK adalah Website Sistem Informasi yang dibuat menggunakan laravel 8 agar para siswa dapat melihat informasi seputar sekolah SMK,event,daftar guru,alumni, PPDB artikel, dan informasi lainnya melalui website dengan mudah.',
      stack: 'Laravel 8, Jquery, MySQL',
      url: 'https://github.com/NoviHe/si_smk',
    },
    {
      id: 7,
      nama: 'Aplikasi Pemesanan Asisten Rumah',
      img: '/img/project/new-asistenrumah.png',
      type: 'Laravel Project',
      desc: 'Asisten Rumah adalah Platform online terbaik di era digital yang akan membantu serta memudahkan Anda untuk mendapatkan asisten rumah tangga yang terpercaya, profesional dan berpengalaman di bidangnya. Anda tidak perlu khwatir semua prosesnya cepat dan kami berusaha memberikan pelayanan yang terbaik.',
      stack: 'Laravel, Jquery, MySQL',
      url: 'https://www.asistenrumah.com',
    },
    {
      id: 8,
      nama: 'BTS Cargo Website',
      img: '/img/project/new-bts-cargo.png',
      type: 'Digitalisaku.com',
      desc: 'BTS Cargo adalah perusahaan yang bergerak dalam bidang jasa pengiriman barang baik padat, cair, alat berat, Kendaraan, dan Hewan. BTS Cargo memiliki beberapa jalur pengiriman diantaranya ada pengiriman lewat darat, laut dan udara.',
      stack: 'PHP Native, Jquery, MySQL',
      url: 'https://bts-cargo.com/',
    },
    {
      id: 9,
      nama: 'TBL Cargo Website',
      img: '/img/project/new-tbl.png',
      type: 'Digitalisaku.com',
      desc: 'TBL Cargo adalah perusahaan yang bergerak dalam bidang jasa pengiriman barang baik padat, cair, alat berat, Kendaraan, dan Hewan. BTS Cargo memiliki beberapa jalur pengiriman diantaranya ada pengiriman lewat darat, laut dan udara.',
      stack: 'PHP Native, Jquery, MySQL',
      url: '#',
    },
    {
      id: 10,
      nama: 'D-Logistic.id',
      img: '/img/project/new-dlog.png',
      type: 'Digitalisaku.com',
      desc: 'D-Log adalah Perusahaan yang bergerak di bidang Pengiriman Barang Domestik / Internasional via Darat, Laut, dan Udara.',
      stack: 'PHP Native, Jquery, MySQL',
      url: 'https://d-logistic.id/',
    },
  ],
  timeline: [
    {
      id: 2,
      title: 'Internship at STMIK Akakom Yogyakarta',
      year: '2019 - 2020',
      desc: '<ul> <li><span>⚪ Creating a Website-based Voting System</span></li> <li><span>⚪ Learn mobile programming with Java language and build a simple application.</span><span>&nbsp;</span></li> <li><span>⚪ Building architecture for IoT (Early Detection of Landslide Movement) project for exhibition</span></li></ul>',
    },
    {
      id: 3,
      title: 'Freelance Software Developer',
      year: '2019 - 2020',
      desc: 'started stepping into software developer with several clients from India, Indonesia and Sweden on Upwork and Personal contract',
    },
    {
      id: 4,
      title: 'Software Developer and IT Staff',
      year: '2020 - 2022',
      desc: '<ul> <li>⚪ Handle and resolve technical issues related to hardware (computers, printers, etc.) and software (operating systems, applications, etc.).</li> <li>⚪ Build, manage and digitally market a website for advertising (AsistenRumah.com) with more than 200 monthly active users in Jakarta and its surroundings.</li> <li>⚪ Responsible for regular data backup and ensuring data security and integrity.</li></ul>',
    },
    {
      id: 5,
      title: 'Backend Developer at SQM Property',
      year: '2022 - now',
      desc: '<ul> <li><span>⚪ Develop API&apos;s using Spring Boot with MySQL databases.</span></li> <li><span>⚪ Collaborate with frontend teams in defining API interfaces and developing features.</span></li> <li><span>⚪ Conduct testing, maintenance, and research to improve system reliability and efficiency.</span></li></ul>',
    },
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/Ryandinulfatah12',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/ryandinulfatah/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/ryandinulfatah12/',
      icon: '/img/icon/instagram.svg',
    },
    {
      id: 4,
      name: 'Facebook',
      link: 'https://www.facebook.com/ryandinulfatah',
      icon: '/img/icon/facebook.svg',
    },
    {
      id: 5,
      name: 'Medium',
      link: 'https://medium.com/@ryandinulfatah',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 6,
      name: 'Email',
      link: 'mailto:dinulfatahryan@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
  techStack: [
    {
      id: 5,
      name: 'MySQL',
      type: 'database',
      icon: '/img/icon/mysql.svg',
      year: '3 years',
    },
    {
      id: 6,
      name: 'Laravel',
      type: 'programming',
      icon: '/img/icon/laravel.svg',
      year: '3 year',
    },
    {
      id: 11,
      name: 'Wordpress',
      type: 'programming',
      icon: '/img/icon/wordpress.svg',
      year: '2 year',
    },
    {
      id: 15,
      name: 'Docker',
      type: 'containerized',
      icon: '/img/icon/docker.svg',
      year: '1 year',
    },
    {
      id: 17,
      name: 'Spring Boot',
      type: 'framework',
      icon: '/img/icon/spring.svg',
      year: '1 year',
    },
    {
      id: 18,
      name: 'Node JS',
      type: 'framework',
      icon: '/img/icon/nodejs.svg',
      year: '6 month',
    },
  ],
  link: [
    {
      id: 1,
      text: 'View My Resume',
      url: 'https://drive.google.com/file/d/1pDeZD3MTPp113KIH6j5fwT39aWjt5WbQ/view?usp=sharing',
    },
    {
      id: 2,
      text: 'My Github',
      url: 'https://github.com/Ryandinulfatah12',
    },
    {
      id: 3,
      text: 'My Instagram',
      url: 'https://www.instagram.com/ryandinulfatah12/',
    },
    {
      id: 4,
      text: 'Send me an email',
      url: 'mailto:dinulfatahryan@gmail.com',
    },
    {
      id: 5,
      text: 'My Linkedin',
      url: 'https://www.linkedin.com/in/ryandinulfatah/',
    },
    {
      id: 6,
      text: 'My Facebook',
      url: 'https://www.facebook.com/ryandinulfatah',
    },
    {
      id: 7,
      text: 'My Medium',
      url: 'https://medium.com/@ryandinulfatah',
    }
  ],
  sertifikasi: [
    {
      id: 1,
      title: 'Job : Frontend-Development Admin Design',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-2.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 2,
      title: 'Job : Need Laravel & MySQL for Develop App',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-1.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 3,
      title: 'Belajar Dasar Pemrograman Web',
      platform: 'Dicoding',
      img: '/img/certificate/new-dasar-web.png',
      url: 'https://www.dicoding.com/certificates/L4PQ3E06VPO1',
    },
    {
      id: 4,
      title: 'Belajar Fundamental Front-end Web Development',
      platform: 'Dicoding',
      img: '/img/certificate/new-frontend-fundamental.png',
      url: 'https://www.dicoding.com/certificates/MEPJLQ1KWZ3V',
    },
    {
      id: 5,
      title: 'Belajar Prinsip Pemrograman SOLID',
      platform: 'Dicoding',
      img: '/img/certificate/new-solid.png',
      url: 'https://www.dicoding.com/certificates/72ZDE5L99PYW',
    },
    {
      id: 6,
      title: 'Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)',
      platform: 'Dicoding',
      img: '/img/certificate/new-aws-dasar.png',
      url: 'https://www.dicoding.com/certificates/ERZR4E6MQZYV',
    },
    {
      id: 7,
      title: 'Basic English Online Course for Programmer',
      platform: 'YEC.CO.ID',
      img: '/img/certificate/new-eng.png',
      url: '#',
    },
    {
      id: 8,
      title: 'Baparekraf Developer Day 2020',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-dev-day-2020.png',
      url: '#',
    },
    {
      id: 9,
      title: 'IDCAMP Virtual Graduation 2019',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-virtual-graduation-2019.png',
      url: '#',
    },
    {
      id: 10,
      title: 'Course Studi Kasus Web Geolocation Laravel & Here Maps API',
      platform: 'Codepolitan',
      img: '/img/certificate/new-codepol.png',
      url: '#',
    },
    {
      id: 11,
      title: 'The Fundamentals of Digital Marketing',
      platform: 'Google Digital Garage',
      img: '/img/certificate/new-google-digital-marketing.png',
      url: '#',
    },
  ],
}
export default userData
