const userData = {
  githubUsername: 'Ryandinulfatah12',
  name: 'Ryan',
  fullname: 'Ryan Dinul Fatah',
  title: 'Software Developer | Fulltime learner | Web Enthusiast',
  country: '🇮🇩 Indonesia',
  desc: 'Im Ryan Dinul Fatah, you can call me Ryan or Iyan. I started liking and learning web development from the 1st grade of high school. Besides that, I also like playing basketball. However, I discontinued my basketball career and decided to study programming, business, and future goals and careers.',
  project: [
    {
      id: 1,
      nama: 'Sistem pendeteksi dini pergerakan tanah longsor',
      img: '/img/project/longsor.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Sistem pendeteksi dini pergerakan tanah longsor SMKN 1 padaherang yang telah saya buat untuk PAMERAN SMK KARYA INOVASI (anak PKL) di STMIK AKAKOM YOGYAKARTA, alat pendeteksi yang bisa dimonitoring melalui web dengan REALTIME.',
      stack: 'C, PHP Native, MySQL, Jquery',
      url: '#',
    },
    {
      id: 2,
      nama: 'Smart Home Project',
      img: '/img/project/smarthome.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Karya Inovasi dari SMK Negeri 1 Padaherang, yang dimana sebuah rumah yang dilengkapi fitur canggih seperti membuka gerbang dengan HP, membuka pintu utama dengan KTP, semua lampu bisa otomatis/manual dari HP, Jemuran dan Kipas Otomatis, serta Monitoring Suhu Ruangan',
      stack: 'C, Javascript, PHP',
      url: '#',
    },
    {
      id: 3,
      nama: 'Aplikasi Kasir Restourant Management',
      img: '/img/project/resto.png',
      type: 'Laravel Project',
      desc: 'Aplikasi Kasir Restourant Management System yang dibuat oleh Saya (Ryan Dinul Fatah) Untuk memenuhi tugas Sekolah tepatnya Project Akhir UJIKOM 2020 saya di SMKN 1 Padaherang ini.',
      stack: 'Laravel, Jquery, MySQL, Bootstrap, Open Source',
      url: 'https://github.com/Ryandinulfatah12/AplikasiKasirRestoran',
    },
    {
      id: 4,
      nama: 'Aplikasi Pengaduan Masyarakat',
      img: '/img/project/pengaduan.png',
      type: 'Laravel Project',
      desc: 'Aplikasi ini merupakan aplikasi yang dapat mengelola pendataan pengaduan dari masyarakat, selain dibuat sesimple mungkin, aplikasi ini juga lumayan dapat bekerja dengan baik untuk dibilang sebuah Aplikasi Pengaduan Masyarakat.',
      stack: 'Laravel, Jquery, MySQL, Bootstrap, Open Source',
      url: 'https://github.com/Ryandinulfatah12/AplikasiPengaduanMasyarakat',
    },
    {
      id: 5,
      nama: 'Sistem informasi Sekolah',
      img: '/img/project/sismk.png',
      type: 'Laravel Project',
      desc: 'Web Media Informasi Sekolah yang dibuat oleh Novi Herlambang . SI_SMK adalah Website Sistem Informasi yang dibuat menggunakan laravel 8 agar para siswa dapat melihat informasi seputar sekolah SMK,event,daftar guru,alumni, PPDB artikel, dan informasi lainnya melalui website dengan mudah.',
      stack: 'Laravel 8, Jquery, MySQL, Bootstrap',
      url: 'https://github.com/NoviHe/si_smk',
    },
    {
      id: 6,
      nama: 'Aplikasi Pemesanan Asisten Rumah',
      img: '/img/project/asistenrumah.png',
      type: 'Laravel Project',
      desc: 'Asisten Rumah adalah Platform online terbaik di era digital yang akan membantu serta memudahkan Anda untuk mendapatkan asisten rumah tangga yang terpercaya, profesional dan berpengalaman di bidangnya. Anda tidak perlu khwatir semua prosesnya cepat dan kami berusaha memberikan pelayanan yang terbaik.',
      stack: 'Laravel, Jquery, MySQL, Bootstrap',
      url: 'https://www.asistenrumah.com',
    },
  ],
  timeline: [
    {
      id: 1,
      title: '🏀 Highschool Basketball Player',
      year: '2014 - 2019',
      desc: 'basketball player in school and club, managed to win the championship, great position and experience',
    },
    {
      id: 2,
      title: '😂 Internship at STMIK Akakom Yogyakarta',
      year: '2019',
      desc: 'running a school internship program at one of the campuses in Yogyakarta, and studying knowledge in the IT, Programming, and other experiences for 5 months.',
    },
    {
      id: 3,
      title: '😃 Freelance Software Developer',
      year: '2019',
      desc: 'started stepping into software developer with several clients from India, Indonesia and Sweden on Upwork and Personal contract',
    },
    {
      id: 4,
      title: '🙂 Software Developer and IT Staff',
      year: '2019',
      desc: 'managing a service company website as well as being the company IT staff at PT. Nurcahya Aulia',
    },
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/Ryandinulfatah12',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/ryandinulfatah/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/ryandinulfatah/',
      icon: '/img/icon/instagram.svg',
    },
    {
      id: 4,
      name: 'Facebook',
      link: 'https://www.facebook.com/ryandinulfatah',
      icon: '/img/icon/facebook.svg',
    },
    {
      id: 5,
      name: 'Medium',
      link: 'https://medium.com/@ryandinulfatah',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 6,
      name: 'Email',
      link: 'mailto:dinulfatahryan@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
  techStack: [
    {
      id: 1,
      name: 'HTML',
      icon: '/img/icon/html5.svg',
      year: '3 years',
    },
    {
      id: 2,
      name: 'CSS',
      icon: '/img/icon/css3.svg',
      year: '3 years',
    },
    {
      id: 3,
      name: 'Javascript',
      icon: '/img/icon/javascript.svg',
      year: '2 years',
    },
    {
      id: 4,
      name: 'PHP',
      icon: '/img/icon/php.svg',
      year: '2 years',
    },
    {
      id: 5,
      name: 'MySQL',
      icon: '/img/icon/mysql.svg',
      year: '2 years',
    },
    {
      id: 6,
      name: 'Laravel',
      icon: '/img/icon/laravel.svg',
      year: '2 year',
    },
    {
      id: 7,
      name: 'React',
      icon: '/img/icon/react.svg',
      year: '2 month',
    },
    {
      id: 8,
      name: 'jQuery',
      icon: '/img/icon/jquery.svg',
      year: '1 year',
    },
    {
      id: 9,
      name: 'SASS/SCSS',
      icon: '/img/icon/sass.svg',
      year: '1 year',
    },
    {
      id: 10,
      name: 'Vue.js',
      icon: '/img/icon/vue.svg',
      year: '2 month',
    },
    {
      id: 11,
      name: 'Wordpress',
      icon: '/img/icon/wordpress.svg',
      year: '3 month',
    },
    {
      id: 12,
      name: 'Figma',
      icon: '/img/icon/figma.svg',
      year: '1 year',
    },
    {
      id: 13,
      name: 'Canva',
      icon: '/img/icon/canva.svg',
      year: '1 year',
    },
  ],
  link: [
    {
      id: 1,
      text: 'View My Resume',
      url: '#',
    },
    {
      id: 2,
      text: 'My Github',
      url: 'https://github.com/Ryandinulfatah12',
    },
    {
      id: 3,
      text: 'My Instagram',
      url: 'https://www.instagram.com/ryandinulfatah/',
    },
    {
      id: 4,
      text: 'Send me an email',
      url: 'mailto:dinulfatahryan@gmail.com',
    },
    {
      id: 5,
      text: 'My Linkedin',
      url: 'https://www.linkedin.com/in/ryandinulfatah/',
    },
    {
      id: 6,
      text: 'My Facebook',
      url: 'https://www.facebook.com/ryandinulfatah',
    },
    {
      id: 7,
      text: 'My Medium',
      url: 'https://medium.com/@ryandinulfatah',
    },
    {
      id: 8,
      text: 'My Blog',
      url: 'https://ryandinulfatah.blogspot.com/',
    },
  ],
}
export default userData
