const userData = {
  githubUsername: 'Ryandinulfatah12',
  name: 'Ryan',
  fullname: 'Ryan Dinul Fatah',
  title: 'Software Developer | Fullstack Developer | Web Enthusiast',
  desc: 'Hi there, im Software Developer who loves to learn new things, besides that, i also like basketball, music, movies and books &#128640;',
  project: [
    {
      id: 1,
      nama: 'Sistem pendeteksi dini pergerakan tanah longsor',
      img: '/img/project/longsor.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Sistem pendeteksi dini pergerakan tanah longsor SMKN 1 padaherang yang telah saya buat untuk PAMERAN SMK KARYA INOVASI (anak PKL) di STMIK AKAKOM YOGYAKARTA, alat pendeteksi yang bisa dimonitoring melalui web dengan REALTIME.',
      stack: 'C, PHP Native, MySQL, Jquery',
    },
    {
      id: 2,
      nama: 'Smart Home Project',
      img: '/img/project/smarthome.png',
      type: 'Internet of Things (IoT) Project',
      desc: 'Karya Inovasi dari SMK Negeri 1 Padaherang, yang dimana sebuah rumah yang dilengkapi fitur canggih seperti membuka gerbang dengan HP, membuka pintu utama dengan KTP, semua lampu bisa otomatis/manual dari HP, Jemuran dan Kipas Otomatis, serta Monitoring Suhu Ruangan',
      stack: 'C, Javascript, PHP',
    },
    {
      id: 3,
      nama: 'Aplikasi Kasir Restourant Management',
      img: '/img/project/resto.png',
      type: 'Laravel Project',
      desc: 'Aplikasi Kasir Restourant Management System yang dibuat oleh Saya (Ryan Dinul Fatah) Untuk memenuhi tugas Sekolah tepatnya Project Akhir UJIKOM 2020 saya di SMKN 1 Padaherang ini.',
      stack: 'Laravel, Jquery, MySQL, Bootstrap',
    },
    {
      id: 4,
      nama: 'Aplikasi Pengaduan Masyarakat',
      img: '/img/project/pengaduan.png',
      type: 'Laravel Project',
      desc: 'Aplikasi ini merupakan aplikasi yang dapat mengelola pendataan pengaduan dari masyarakat, selain dibuat sesimple mungkin, aplikasi ini juga lumayan dapat bekerja dengan baik untuk dibilang sebuah Aplikasi Pengaduan Masyarakat.',
      stack: 'Laravel, Jquery, MySQL, Bootstrap',
    },
  ],
  timeline: [
    {
      id: 1,
      title: '🏀 Highschool Basketball Player',
      year: '2014 - 2019',
      desc: 'basketball player in school and club, managed to win the championship, great position and experience',
    },
    {
      id: 2,
      title: '😂 Internship at STMIK Akakom Yogyakarta',
      year: '2019',
      desc: 'running a school internship program at one of the campuses in Yogyakarta, and studying knowledge in the IT, Programming, and other experiences for 5 months.',
    },
    {
      id: 3,
      title: '😃 Freelance Software Developer',
      year: '2019',
      desc: 'started stepping into software developer with several clients from India, Indonesia and Sweden on Upwork and Personal contract',
    },
    {
      id: 4,
      title: '🙂 Software Developer and IT Staff',
      year: '2019',
      desc: 'managing a service company website as well as being the company IT staff at PT. Nurcahya Aulia',
    },
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/Ryandinulfatah12',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/ryandinulfatah/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/ryandinulfatah/',
      icon: '/img/icon/instagram.svg',
    },
    {
      id: 4,
      name: 'Facebook',
      link: 'https://www.facebook.com/ryandinulfatah',
      icon: '/img/icon/facebook.svg',
    },
    {
      id: 5,
      name: 'Medium',
      link: 'https://medium.com/@ryandinulfatah',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 6,
      name: 'Email',
      link: 'mailto:dinulfatahryan@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
}
export default userData
